### ISSUE TITLE
在估计参数时是否存在其它有监督数据的泄漏

### ISSUE THREAD

**Issue by ideal-123** [mrflogs/ICLR24#4]
你好，感谢您发布的代码！想请教一个问题。
我发现main_few_shots.py中在45-51行提到了“augment_epoch‘，即多次从训练集中采样数据，这些采样数据参与了后续的参数估计。想问下这里是否有除了当前Few-shot任务外的有监督数据泄漏呢？如果是引入了其它的有监督数据，few-shot tasks还可以用本文提出的GDA方法处理嘛？

**Comment by mrflogs** [comment]
不是采样，是同一个few-shot数据集的不同增广。

**Comment by ideal-123** [comment]
好的，明白了，谢谢！
